export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const REQUEST_USER_START = "REQUEST_USER_START";
export const REQUEST_USER_SUCCESS = "REQUEST_USER_SUCCESS";
export const REQUEST_USER_FAIL = "REQUEST_USER_FAIL";

export const UPDATE_USER_START = "UPDATE_USER_START";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const REQUEST_USERS_START = "REQUEST_USERS_START";
export const REQUEST_USERS_SUCCESS = "REQUEST_USERS_SUCCESS";
export const REQUEST_USERS_FAIL = "REQUEST_USERS_FAIL";

export const REPORT_ERROR_START = "REPORT_ERROR_START";
export const REPORT_ERROR_SUCCESS = "REPORT_ERROR_SUCCESS";
export const REPORT_ERROR_FAIL = "REPORT_ERROR_FAIL";

export const UPDATE_REPORT_ERROR_START = "UPDATE_REPORT_ERROR_START";
export const UPDATE_REPORT_ERROR_SUCCESS = "UPDATE_REPORT_ERROR_SUCCESS";
export const UPDATE_REPORT_ERROR_FAIL = "UPDATE_REPORT_ERROR_FAIL";

export const REQUEST_ERRORS_START = "REQUEST_ERRORS_START";
export const REQUEST_ERRORS_SUCCESS = "REQUEST_ERRORS_SUCCESS";
export const REQUEST_ERRORS_FAIL = "REQUEST_ERRORS_FAIL";

export const REQUEST_SINGLE_ERROR_START = "REQUEST_SINGLE_ERROR_START";
export const REQUEST_SINGLE_ERROR_SUCCESS = "REQUEST_SINGLE_ERROR_SUCCESS";
export const REQUEST_SINGLE_ERROR_FAIL = "REQUEST_SINGLE_ERROR_FAIL";
